import Foundation

struct TicketAutomation: Sendable {
    let ticketID: String
    let taskTracker: any TaskTracker
    let githubService: GitHubService
    let aiAgent: any AIAgent
    let promptTemplate: PromptTemplate
    let skipTests: Bool
    let draft: Bool

    init(
        ticketID: String,
        taskTracker: any TaskTracker,
        githubService: GitHubService,
        aiAgent: any AIAgent,
        promptTemplate: PromptTemplate = DefaultPromptTemplate(),
        skipTests: Bool = false,
        draft: Bool = false
    ) {
        self.ticketID = ticketID
        self.taskTracker = taskTracker
        self.githubService = githubService
        self.aiAgent = aiAgent
        self.promptTemplate = promptTemplate
        self.skipTests = skipTests
        self.draft = draft
    }

    /// Convenience initializer using Configuration
    init(
        ticketID: String,
        taskTracker: any TaskTracker,
        config: Configuration,
        githubToken: String?,
        skipTests: Bool = false,
        draft: Bool = false
    ) {
        self.ticketID = ticketID
        self.taskTracker = taskTracker
        self.githubService = GitHubService(
            configuration: config.getGitHubConfiguration(token: githubToken, draft: draft)
        )
        self.aiAgent = config.getAIAgent()
        self.promptTemplate = DefaultPromptTemplate()
        self.skipTests = skipTests
        self.draft = draft
    }

    func execute() async throws {
        print("🎫 Fetching ticket: \(ticketID)")
        let issue = try await taskTracker.fetchIssue(ticketID)

        print("\n📋 Task: \(issue.title)")

        print("\n🔄 Moving ticket to 'In Progress'...")
        do {
            try await taskTracker.changeStatus(ticketID, to: "In Progress")
        } catch AutomationError.invalidStatus(let requested, let available) {
            print("⚠️  Warning: Could not move to '\(requested)'. Available statuses: \(available.joined(separator: ", "))")
        } catch {
            print("⚠️  Warning: Could not change status: \(error.localizedDescription)")
        }

        print("\n🤖 Running \(aiAgent.name)...")
        let prompt = buildPrompt(for: issue)
        let agentResult = try await aiAgent.execute(
            prompt: prompt,
            context: AIAgentContext()
        )

        if !skipTests {
            print("\n🧪 Running tests...")
            try await runTests()
        }

        print("\n🌿 Creating branch and pushing changes...")
        let sanitizedTicketID = ticketID.sanitizedForBranchName()
        let branch = "feature/\(sanitizedTicketID)"
        try await githubService.createBranch(
            name: branch,
            from: githubService.configuration.baseBranch,
            in: nil
        )
        try await githubService.commitAndPush(
            message: "[\(ticketID)] Automated implementation",
            branch: branch,
            in: nil
        )

        print("\n📬 Creating pull request...")
        let prResult = try await githubService.createPullRequest(
            PullRequestParams(
                title: "[\(ticketID)] \(issue.title)",
                body: buildPRBody(issue: issue, agentOutput: agentResult.output),
                branch: branch,
                baseBranch: githubService.configuration.baseBranch,
                draft: draft
            )
        )

        print("\n✅ Updating ticket...")
        try await taskTracker.updateIssue(ticketID, prURL: prResult.url)

        print("\n🔄 Moving ticket to 'In Review'...")
        do {
            try await taskTracker.changeStatus(ticketID, to: "In Review")
        } catch AutomationError.invalidStatus(let requested, let available) {
            print("⚠️  Warning: Could not move to '\(requested)'. Available statuses: \(available.joined(separator: ", "))")
        } catch {
            print("⚠️  Warning: Could not change status: \(error.localizedDescription)")
        }

        print("\n🎉 Done! PR created: \(prResult.url)")
    }

    func buildPrompt(for issue: TaskIssue) -> String {
        let variables = PromptVariables(from: issue)
        return promptTemplate.render(with: variables)
    }

    func runTests() async throws {
        let output = try await Shell.run("swift", "test")

        if output.contains("FAILED") || output.contains("error:") {
            throw AutomationError.testsFailed
        }

        print("✅ All tests passed")
    }

    func buildPRBody(issue: TaskIssue, agentOutput: String) -> String {
        """
        Resolves [\(issue.id)](\(taskTracker.baseURL)/issue/\(issue.id))

        ## Summary
        \(issue.title)

        ## Description
        \(issue.description ?? "")

        ## Implementation Details
        \(agentOutput)

        ---
        🤖 This PR was automatically generated by entrust using \(aiAgent.name)
        """
    }
}
